#!/usr/bin/python3
import sys
import re

if __name__ == "__main__":
    stdin_lines = [x.strip("\n") for x in sys.stdin]
    # Make sure we got something to match
    if len(sys.argv) != 2:
        raise ValueError("No value to match have been provided")
    match_param = sys.argv[1]

    in_section = False
    section_min_indent = 0
    for line in stdin_lines:
        first_line_in_sec = False
        if match_param in line and not in_section:  # Start a new section
            first_line_in_sec = True
            in_section = True
            section_min_indent = 0
            for c in line:
                if c == " " or c == "   ":
                    section_min_indent += 1

        if in_section and not first_line_in_sec:  # Logic to end section
            line_indent = 0
            for c in line:
                if c == " " or c == "   ":
                    line_indent += 1

            if not line_indent > section_min_indent:
                in_section = False

        if in_section:  # Print line if still in section
            print(line)
